# Generated by Django 4.1.2 on 2022-11-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
