# Generated by Django 4.1.2 on 2022-11-02 14:32

import accounts.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, help_text='2 mb gacha bo`lgan rasm yuklang', null=True, upload_to='users_images', validators=[accounts.services.validate_image, accounts.services.custom_validator], verbose_name='Profil rasmi'),
        ),
    ]
