# Generated by Django 4.1.2 on 2022-11-07 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('book', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('sex', '6'), ('other', 'other')], max_length=20, verbose_name='Kitob: ')),
                ('from_lesson', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qaysi darsdan: ')),
                ('to_lesson', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qaysi darsgacha: ')),
                ('count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Soni')),
                ('words', models.TextField(verbose_name='So`zlarni bo`sh joy bilan ajratib vergul ishlatmay kiriting')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Izoh uchun joy: ')),
                ('similarity', models.FloatField(blank=True, default=0, null=True)),
                ('is_verifyed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('for_all_students', models.BooleanField(blank=True, null=True, verbose_name='Hamma student uchunmi?')),
                ('text', models.TextField(verbose_name='Buyruq matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images', validators=[main.services.validate_image, main.services.custom_validator], verbose_name='Fotosurat (ixtiyoriy)')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='task_files', verbose_name='Fayl (ixtiyoriy)')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_user', to='accounts.student', verbose_name='Bitta student uchun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', models.TextField(verbose_name='Javob yozing')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskresult', to='main.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskresult', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('word', models.CharField(blank=True, max_length=100, null=True, verbose_name='so`z')),
                ('word_translation', models.CharField(blank=True, max_length=100, null=True, verbose_name='tarjimasi')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reach_images', validators=[main.services.validate_image, main.services.custom_validator], verbose_name='Fotosurat (ixtiyoriy)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reachment', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dayplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayplan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', models.TextField(verbose_name='matn')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='chat_files', verbose_name='fayl')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
