# Generated by Django 4.1.2 on 2022-11-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='for_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='for_students',
        ),
        migrations.AddField(
            model_name='task',
            name='for_all_students',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hamma student uchunmi?'),
        ),
    ]
