# Generated by Django 4.1.2 on 2022-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_report_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(max_length=200, verbose_name='Izoh uchun joy: '),
        ),
    ]
