# Generated by Django 4.1.2 on 2022-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_reportitem_comment_remove_reportitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Izoh uchun joy: '),
        ),
    ]
