# Generated by Django 4.1.2 on 2022-11-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_report_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='similarity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
