# Generated by Django 4.1.2 on 2022-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_report_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Izoh uchun joy: '),
        ),
    ]
