# Generated by Django 4.1.2 on 2022-11-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_alter_user_role'),
        ('main', '0012_alter_report_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reachment', to='accounts.student'),
        ),
    ]
