# Generated by Django 4.1.2 on 2022-11-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_alter_user_role'),
        ('main', '0013_alter_reachment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Buyruq matni'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_user', to='accounts.student', verbose_name='Bitta student uchun'),
        ),
    ]
